### ISSUE TITLE
Dev site notice contains poor markup

### ISSUE THREAD

**Issue by ryanshoover** [wpengine/geoip#36]
The notice that appears on a dev site includes HTML. But since we're running all notices through `esc_html` [code](https://github.com/wpengine/geoip/blob/master/wpengine-geoip.php#L639), the < and > are getting converted to their HTML entitites. Let's switch from `esc_html` to `wpautop` or come up with a more elegant escaping solution here. Or kill the HTML in the notice (?)

![Bad notice HTML](https://user-images.githubusercontent.com/1707424/36698092-91d74138-1b0e-11e8-9447-027299a2b042.png)

**Comment by ryanshoover** [comment]
I can take this but not sure when I'll get to it. @nateinaction, if you want to do this, go for it.

**Comment by nateinaction** [comment]
@ryanshoover Since we expect `$notice` to contain HTML why would we escape it?

Can I just remove `esc_html`? https://github.com/wpengine/geoip/blob/cc7df1f07d5e1f321d80fa72e9ae5714381a92a6/wpengine-geoip.php#L639

**Comment by ryanshoover** [comment]
@nateinaction WordPress strongly recommends [escaping all text before output](https://codex.wordpress.org/Validating_Sanitizing_and_Escaping_User_Data#Escaping:_Securing_Output). For our code to conform to [WPCS standards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards), we need to escape all output before echoing it. 

Honestly, there's no chance of of this particular code being compromised as the notice is defined in the file and isn't filtered or altered before being output. But best practice is to *always* escape before output.
