### ISSUE TITLE
Update Installer Notice

### ISSUE THREAD

**Issue by stevenkword** [wpengine/geoip#7]
We should change the error message copy to say "GeoIP will only function..." instead of "This plugin will only function..." so that the admin notice is more explicit.

**Comment by stephen-lin** [comment]
Maybe something like this:

Please note - GeoIP is only available on WP Engine accounts once the proper server settings are enabled. This will not function outside of the WP Engine environment. Plugin deactivated.

**Comment by nateinaction** [comment]
@ryanshoover @stevenkword The notice has been changed to specifically call out the GeoIP plugin. I think this issue can be closed.

**Comment by ryanshoover** [comment]
Good call
